export const FAVOURITE_REQ = "FAVOURITE_REQ";
export const FAVOURITE_SUCCESS = "FAVOURITE_SUCCESS";
export const FAVOURITE_ERROR = "FAVOURITE_ERROR ";

export const SEARCH_FAVOURITE_USER_REQ = "SEARCH_FAVOURITE_USER_REQ";
export const SEARCH_FAVOURITE_USER_SUCCESS = "SEARCH_FAVOURITE_USER_SUCCESS";
export const SEARCH_FAVOURITE_USER_ERROR = "SEARCH_FAVOURITE_USER_ERROR ";

export const PHONEBOOK_REQ = "PHONEBOOK_REQ";
export const PHONEBOOK_SUCCESS = "PHONEBOOK_SUCCESS";
export const PHONEBOOK_ERROR = "PHONEBOOK_ERROR ";

export const PHONEBOOK_DELETE_REQ = "PHONEBOOK_DELETE_REQ";
export const PHONEBOOK_DELETE_SUCCESS = "PHONEBOOK_DELETE_SUCCESS";
export const PHONEBOOK_DELETE_ERROR = "PHONEBOOK_DELETE_ERROR ";

export const PHONEBOOK_UPDATE_REQ = "PHONEBOOK_UPDATE_REQ";
export const PHONEBOOK_UPDATE_SUCCESS = "PHONEBOOK_UPDATE_SUCCESS";
export const PHONEBOOK_UPDATE_ERROR = "PHONEBOOK_UPDATE_ERROR ";

export const JOBLIST_REQ = "JOBLIST_REQ";
export const JOBLIST_SUCCESS = "JOBLIST_SUCCESS";
export const JOBLIST_ERROR = "JOBLIST_ERROR ";

export const JOBLIST_CREATED_REQ = "JOBLIST_CREATED_REQ";
export const JOBLIST_CREATED_SUCCESS = "JOBLIST_CREATED_SUCCESS";
export const JOBLIST_CREATED_ERROR = "JOBLIST_CREATED_ERROR ";

