
export const JOBLIST_REQ = "JOBLIST_REQ";
export const JOBLIST_SUCCESS = "JOBLIST_SUCCESS";
export const JOBLIST_ERROR = "JOBLIST_ERROR ";

export const JOBLIST_CREATED_REQ = "JOBLIST_CREATED_REQ";
export const JOBLIST_CREATED_SUCCESS = "JOBLIST_CREATED_SUCCESS";
export const JOBLIST_CREATED_ERROR = "JOBLIST_CREATED_ERROR ";

export const JOBLIST_ORDER_REQ = "JOBLIST_ORDER_REQ";
export const JOBLIST_ORDER_SUCCESS = "JOBLIST_ORDER_SUCCESS";
export const JOBLIST_ORDER_ERROR = "JOBLIST_ORDER_ERROR ";

export const REPORT_REQ = "REPORT_REQ";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_ERROR = "REPORT_ERROR ";

